### ISSUE TITLE
Bot gives no response nor is any error in the server shown

### ISSUE THREAD

**Issue by bottest123** [karipov/cross-prom#1]
Hello ...

 I deployed the bot but it dosent seem to respond on any message nor /start or /help..

Please check into this I have added the screenshots below 

![Screenshot_20190609-085756](https://user-images.githubusercontent.com/41206183/59154646-c1a32c00-8a94-11e9-8e34-c871f12842e2.jpg)
![Screenshot_20190609-085801](https://user-images.githubusercontent.com/41206183/59154647-c536b300-8a94-11e9-80b9-18c408007c99.jpg)

**Comment by karipov** [comment]
Hi,

this was a very old project of mine that I am not supporting anymore. I'll move it to the archive, but if you really need to use it, there are some steps I'd suggest taking.

1. Revert back to polling (server stuff doesn't work)
2. Implement a nice database backend, with something like [sqlite](https://docs.python.org/3/library/sqlite3.html). This one currently uses a text file (I know, it's horrific)

Good luck!
